HTTP:
  Port: ":5000"
  Development: true
  ReadTimeout: 10
  WriteTimeout: 10
  MaxConnectionIdle: 10
  MaxConnectionAge: 10

PostgreSQL:
  PostgresqlHost: localhost
  PostgresqlPort: 5432
  PostgresqlUser: postgres
  PostgresqlPassword: postgres
  PostgresqlDBName: postgres
  PostgresqlSslmode: "disable"
